### ISSUE TITLE
Крафт листы

### ISSUE THREAD

**Issue by EndrII** [EndrII/Space_engine#3]
Не работают таблицы отображения листов крафта в редакторе объектов.

**Comment by EndrII** [comment]
В объекты добавляются крафт листы. 
нужно заменить QTableWidget на QTableViev и перегрузить модель отображения крафт листов.

**Comment by EndrII** [comment]
настроить обновление в крафт листе после добавления и удаления очередного элемента.

**Comment by usermeme** [comment]
woooow

**Comment by EndrII** [comment]
Крафт листы теперь отображают добавленные элементы.
Нужно поправить модель на редактирования количества, и проверить почему не отображаются иконки. <br>
commit 5ca8d61b974d9b0c91e980647189426e5c051d77

**Comment by EndrII** [comment]
проблема с крафт листами решена коммит 6a8bbc66d904663a4de7b54deefefa0f73748b0b
